const root = document.querySelector('#game');
const start = document.querySelector('#start');
const name = document.querySelector('#game-name');
const status = document.querySelector('#game-status');
const hint = document.querySelector('#hint');
let cleanup = () => {};
const games = {
  reflex: { title:'NEON REFLEX', hint:'Clique no núcleo rosa antes que ele desapareça.', run: neonReflex },
  dodge: { title:'PIXEL DODGE', hint:'Use ← → ou A D para desviar das ameaças.', run: pixelDodge },
  memory: { title:'MEMORY PULSE', hint:'Encontre todos os pares de energia.', run: memoryPulse },
};
function reset(){ cleanup(); root.replaceChildren(); }
function setGame(key){ const game=games[key]; reset(); name.textContent=game.title; hint.textContent=game.hint; status.textContent='clique em iniciar'; start.onclick=()=>{reset(); cleanup=game.run();}; document.querySelectorAll('[data-game]').forEach(b=>b.classList.toggle('active',b.dataset.game===key)); }
function neonReflex(){ let score=0,time=15,alive=true; status.textContent=`tempo ${time}s · pontos ${score}`; const timer=setInterval(()=>{ if(!alive)return; time--; status.textContent=`tempo ${time}s · pontos ${score}`; if(time<=0){alive=false;clearInterval(timer);root.replaceChildren();status.textContent=`fim · ${score} pontos`;}},1000); function spawn(){if(!alive)return;const o=document.createElement('button');o.className='orb';o.ariaLabel='alvo';o.style.left=`${8+Math.random()*78}%`;o.style.top=`${10+Math.random()*70}%`;o.onclick=()=>{score++;o.remove();spawn();status.textContent=`tempo ${time}s · pontos ${score}`};root.append(o);setTimeout(()=>{o.remove();if(alive)spawn()},950)}spawn();return()=>{alive=false;clearInterval(timer)};}
function pixelDodge(){ let x=47,score=0,alive=true;const ship=document.createElement('div');ship.className='ship';ship.style.bottom='18px';root.append(ship);const draw=()=>ship.style.left=`${x}%`;draw();const move=e=>{if(['ArrowLeft','a','A'].includes(e.key))x=Math.max(0,x-6);if(['ArrowRight','d','D'].includes(e.key))x=Math.min(94,x+6);draw()};document.addEventListener('keydown',move);const hazards=[];const loop=setInterval(()=>{if(!alive)return;score++;status.textContent=`sobreviveu ${score}s`;const h=document.createElement('div');h.className='hazard';h.style.left=`${Math.random()*90}%`;h.style.top='-30px';root.append(h);hazards.push({el:h,y:-30});},850);const frame=setInterval(()=>{if(!alive)return;hazards.forEach((h,i)=>{h.y+=6;h.el.style.top=`${h.y}px`;const a=h.el.getBoundingClientRect(),b=ship.getBoundingClientRect();if(a.left<b.right&&a.right>b.left&&a.bottom>b.top&&a.top<b.bottom){alive=false;status.textContent=`fim · ${score}s`;}});if(!alive){clearInterval(loop);clearInterval(frame)}},35);return()=>{alive=false;clearInterval(loop);clearInterval(frame);document.removeEventListener('keydown',move)};}
function memoryPulse(){const values=['✦','◈','◉','△','✦','◈','◉','△'].sort(()=>Math.random()-.5);const grid=document.createElement('div');grid.className='memory-grid';root.append(grid);let open=[],matches=0,locked=false;status.textContent='pares 0/4';values.forEach((value,index)=>{const b=document.createElement('button');b.className='memory-card';b.textContent=value;b.onclick=()=>{if(locked||b.classList.contains('open')||b.classList.contains('matched'))return;b.classList.add('open');open.push({b,value});if(open.length===2){locked=true;const [a,c]=open;if(a.value===c.value){a.b.classList.replace('open','matched');c.b.classList.replace('open','matched');matches++;open=[];locked=false;status.textContent=`pares ${matches}/4`;if(matches===4)status.textContent='rota concluída · 4/4';}else setTimeout(()=>{a.b.classList.remove('open');c.b.classList.remove('open');open=[];locked=false},650);}};grid.append(b)});return()=>{};}
document.querySelectorAll('[data-game]').forEach(button=>button.onclick=()=>setGame(button.dataset.game));setGame('reflex');
